apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: tmf652
  description: TMF 652 Resource Order Management-v4.0.0
  tags:
    - tmf
    - tmf639
  links:
    - url: https://openslice-1.euprojects.net/tmf-api/swagger-ui/index.html?urls.primaryName=tmf-api-652-ResourceOrderManagement-v4.0.0
      title: Swagger
      icon: code
spec:
  type: openapi
  lifecycle: experimental
  owner: UOP
  definition:
    $text: https://openslice-1.euprojects.net/tmf-api/v3/api-docs/tmf-api-652-ResourceOrderManagement-v4.0.0