apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: tmf634
  description: TMF 634 Resource Catalog Management
  tags:
    - tmf
    - tmf639
spec:
  type: openapi
  lifecycle: experimental
  owner: UOP
  definition:
    $text: ./tmf-634-api.oas.yaml
    
